### ISSUE TITLE
Fixing Scoring 

### ISSUE THREAD

**Issue by MrPlow254** [LGBT-PlexPlugins/plex-gay-metadata-agent#24]
Going to combine all the bundles into one to allow for titles to have a score set to 100. This will prevent updating in the future if the title is correct.

**Comment by hawkeyefla** [comment]
Oh, very nice.  And also, if it becomes a single bundle, I believe it can be more easily added to the Unsupported App portion of the Web Tools, since that can query a Git repository.  That will be the first thing I will test once it's a single bundle.

**Comment by hawkeyefla** [comment]
Random thought.  Using the Fix Incorrect Match, would there be any way to pass the URL of a clip to the agent?  Some of Helix's older clips are so basically named like "Devon & Tyler" that it's pretty much impossible for the agent to make a match, but if the full URL of the clip could be passed to the agent, a match could be found for these older titles.

**Comment by MrPlow254** [comment]
> Using the Fix Incorrect Match, would there be any way to pass the URL of a clip to the agent?
I don't know what you mean by this. The agent already gets the URL.

Can you elaborate a little bit more. I think I know what you are saying, but unsure.

As a side note it might pull up the wrong title but the score won't be set to 100 unless it is an exact match. This also will be a while before I code this. It might not need to be in one bundle. I have just read from some places that scores only work on primary agents. If you can throw some thought about what to do I'll think about it. 

Currently my plan is to have options to turn on/off studios vs having different bundles. It will also pull from Helix and Staxus first then from AEBN.

**Comment by hawkeyefla** [comment]
We'll use my previous example of Devon & Tyler.  On Helix's website the video's title is "Devon & Tyler" and I have "Devon & Tyler.mkv"  Since Helix's search doesn't accept the &, I can't get it to match.  I've tried searches of "devon tyler" as well as "devon and tyler."  But we do know the URL for the video is https://www.helixstudios.net/video/1165/devon-tyler.html

Inside the page for a video in PMS there is the option to Fix Incorrect Match which as the two options of "Search Options" and "Auto Match"  Search Options lets you put a title in to try and fix the match.  Works great with The Movie Database, which is how I already get my full length Helix movies to match from TMD.  If there was a way to put the URL of https://www.helixstudios.net/video/1165/devon-tyler.html into the Title search field and have the agent recognize the https and not even have to search, just set that URL into video_url.  
I'm not much of a coder, so I'm really not sure if this can be done, but it was an idea I had today.  Thankfully most of the newer Helix titles have unique names (Guess they hired someone that was more creative in naming), but I have a bunch of older videos that are as simple as Model & Model on their site.
